services:
  - name: renderhook-backend
    github:
      repo: paupenin/renderhook
      branch: main
    dockerfile_path: .docker/Dockerfile.backend
    environment_slug: docker
    http_port: 8080
    routes:
      - path: /
