name: Deploy to DigitalOcean Container Registry

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".docker/Dockerfile.backend"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com
          username: _
          password: ${{ secrets.DO_TOKEN }}

      - name: Build and push Docker image to DOCR
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./.docker/Dockerfile.backend
          push: true
          tags: registry.digitalocean.com/renderhook/backend:latest
